version: "3.3"

services:
  vrww:
    build: .
    entrypoint: "nodemon /app/src/index.js --watch /app --legacy-watch"
    container_name: vrww
    network_mode: bridge
    volumes:
      - ./:/app
    links:
      - vrww-db
      - vrww-db-test
    ports:
      - "80:80"

  vrww-db:
    image: postgres:11
    container_name: vrww-db
    network_mode: bridge
    volumes:
      - ./.vol/vrww-db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vrww
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret

  vrww-db-test:
    image: postgres:11
    container_name: vrww-db-test
    network_mode: bridge
    volumes:
      - ./.vol/vrww-db-test:/var/lib/postgresql/data
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: vrww
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
