apiVersion: v1
kind: Service
metadata:
  name: vrww
  labels:
    app: vrww
spec:
  selector:
    app: vrww
    tier: web
  ports:
    - name: vrww
      port: 80
      targetPort: 80
  type: NodePort
