apiVersion: v1
kind: Service
metadata:
  name: vrwww-load-balancer
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "ba30c66d-2b9f-46eb-a2d4-4c38e82cdac3"
spec:
  type: LoadBalancer
  selector:
    app: vrww
  ports:
    - protocol: TCP
      port: 443
      targetPort: 80
      name: https
